version: '3'
services:
    redis:
        image: redis:latest
        container_name: redis
        ports:
            - 6379:6379
        volumes:
            - ./redis/data:/var/lib/redis
            - ./redis.conf:/redis.conf
        command: [ "redis-server", "/redis.conf" ]
